### ISSUE TITLE
[BUG] Developing linked packages experience is bad.

### ISSUE THREAD

**Issue by mshima** [npm/arborist#247]
# What / Why

Developing coupled packages linked with npm link is not optimal.
1. `npm link` breaks the linked package.
2. `npm link` removes others links. (regression from npm 6)

## When

Developing/testing linked packages together

## Where

* n/a

### Current Behavior

* n/a

### Steps to Reproduce

Preparing the environment
```
git clone https://github.com/yeoman/environment.git
cd environment
npm ci
npm link
cd ..
git clone https://github.com/yeoman/generator.git
cd generator
npm ci
npm link
cd ..
git clone https://github.com/yeoman/yeoman-test.git
cd yeoman-test
npm ci
npm link
cd ..
```

Reset the environment
```
cd environment
npm ci
cd ..
cd generator
npm ci
cd ..
cd yeoman-test
npm ci
cd ..
```

1. `npm link` breaks the linked package.
```
cd yeoman-test
npm link yeoman-generator
npm test
```
output:
```
Error: Cannot find module 'semver'
Require stack:
- /Users/mshima/git/reproduce/generator/lib/index.js
- /Users/mshima/git/reproduce/yeoman-test/test/helpers.js
```
Workaround go to generator folder and execute `npm ci`

2. `npm link` removes others links. (regression from npm 6)

```
cd yeoman-test
npm link yeoman-generator
ls -l node_modules/yeoman-*
```
output:
```
lrwxr-xr-x  1 mshima  staff  15  6 Mar 12:14 node_modules/yeoman-generator -> ../../generator

node_modules/yeoman-environment:
total 24
drwxr-xr-x   4 mshima  staff   128  6 Mar 12:14 cli
.
.
.
```

```
npm link yeoman-environment
ls -l node_modules/yeoman-*
```
output:
```
lrwxr-xr-x  1 mshima  staff  17  6 Mar 12:20 node_modules/yeoman-environment -> ../../environment

node_modules/yeoman-generator:
total 32
-rw-r--r--   1 mshima  staff  1292 26 Out  1985 LICENSE
drwxr-xr-x   5 mshima  staff   160  6 Mar 12:20 lib
.
.
.
```

Workaround: link both together `npm link yeoman-generator yeoman-environment`

```
ls -l node_modules/yeoman-*
lrwxr-xr-x  1 mshima  staff  17  6 Mar 12:20 node_modules/yeoman-environment -> ../../environment
lrwxr-xr-x  1 mshima  staff  15  6 Mar 12:22 node_modules/yeoman-generator -> ../../generator
```

### Expected Behavior

* n/a

## Who

* n/a

## References

* n/a

**Comment by ljharb** [comment]
This repo is for arborist; this sounds more like something that belongs on https://github.com/npm/rfcs or https://github.com/npm/cli

**Comment by isaacs** [comment]
@ljharb Well, to be fair, if there's a bug in the workflows described, it almost certainly is a bug in Arborist, so this isn't an _entirely_ inappropriate place to post it.

@mshima We just published a new npm version with a fix that might be relevant here.  Can you `npm i npm -g` and retry?  If it still occurs, please let us know.  In the meantime, I'll try to reproduce and see if anything jumps out at me.  I think I can figure out what you're going for, but a description of the expected behavior would be good, too.

**Comment by mshima** [comment]
@isaacs I've tried the npm `7.6.2` and the problem persisted.
I've updated the expected behavior but it's really generic, since I don't know the consequence of the real fix.

IMO the real fix is to don't touch manually linked leafs.
Manually linked modules should be considered a valid (npm ci was executed) and independent tree and should not touched.

#### First problem:
It happens when a dependency of a linked module is deduped and moved down the tree.
The linked module have a dependency on `semver`, which became unreachable to this module since it deduped from:
`node_modules/yeoman-environment/node_modules/semver`
to
`node_modules/semver`

The consequence is that `yeoman-environment` cannot find `semver` because it's not in it's node_modules tree anymore.

#### Second problem:
A manually linked module should not be overridden, in this case a second `npm link` removed the first link.

The first problem happens in npm 6, while the second is a regression.
